"""reinit

Revision ID: 80ad669861c6
Revises: 44a5aac6e75a
Create Date: 2023-05-24 09:54:22.871830-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ad669861c6'
down_revision = '44a5aac6e75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
